- hosts: servers
  become: yes
  roles:
    - common-all
    - icinga2
    - backup-client
#    - mysqlbackup
    - ufw
    - unattended-upgrades
    - sshuserkeys
    - tripwire
  tags:
    - minimum
- hosts: php-servers
  become: yes
  roles:
    - php
  tags:
    - php
- hosts: git-servers
  become: yes
  roles:
    - gitmonitoring
  tags:
    - git-monitoring
- hosts: kvm-servers
  become: yes
  roles:
    - kvm-server
  tags:
    - kvm-server
- hosts: icinga-servers
  become: yes
  roles:
    - php
    - icinga2
  tags:
   - icinga2
   - icinga 
- hosts: gitlab-servers
  become: yes
  roles:
    - gitlab
  tags:
    - gitlab

- hosts: aegir-servers
  become: yes
  roles:
    - aegir
  tags:
    - aegir

- hosts: identity-servers
  become: yes
  roles:
    - keycloak
  tags:
    - keycloak

- hosts: local-servers
  become: yes
  roles:
    - php
    - terraform
    - azure
  vars:
    version:
      terraform: 0.12.29
