- hosts: icinga-satellite
  become: yes
  roles:
    - icinga2
  tags:
    - icinga
    - icinga2

- hosts: all
  become: yes
  roles:
    - backup-client
  tags:
    - backup-client
- hosts: servers
  become: yes
  roles:
    - common-all
    - backup-client
#    - mysqlbackup
    - ufw
    - unattended-upgrades
#    - sshuserkeys
  tags:
    - minimum
- hosts: php-servers
  become: yes
  roles:
    - php
  tags:
    - php
- hosts: kvm-servers
  become: yes
  roles:
    - kvm-server
  tags:
    - kvm-server
- hosts: localhost
  become: yes
  roles: 
    - php
    - common-all
    - backup-client
  tags:
    - php
