- hosts: servers
  become: yes
  roles:
    - common-all
    - icinga2
    - backup-client
#    - mysqlbackup
    - ufw
    - unattended-upgrades
    - sshuserkeys
  tags:
    - minimum
- hosts: php-servers
  become: yes
  roles:
    - php
  tags:
    - php
- hosts: kvm-servers
  become: yes
  roles:
    - kvm-server
  tags:
    - kvm-server
- hosts: localhost
  become: yes
  roles: 
    - php
    - common-all
    - backup-client
  tags:
    - php
- hosts: icinga-servers
  become: yes
  roles:
    - php
    - icinga2
  tags:
   - icinga2
   - icinga 
- hosts: gitlab-servers
  become: yes
  roles:
    - gitlab
  tags:
    - gitlab
