---
# Backups operate in "pull" mode from the backup-server.
# Therefore, we mostly need to configure the mysqldump on the client,
# but we also delegate to the backup-server the configuration of
# a rdiff-backup pull for backupninja.

- apt: update_cache=yes
  tags:
    - packages

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - backupninja
    - borgbackup
  tags:
    - packages

# Deploy backupninja rdiff config to onsite backup-server
- name: Backupninja | deploy backup templates
  template:
    src: "{{ item }}"
    dest: "/etc/backup.d/"
    mode: 0600
    owner: root
  with_fileglob:
    - ../templates/etc/backup.d/*
  tags:
    - backup-client
    - backup-client-configuration
