---

# We deploy our sources.list to include "contrib"
- name: common-all | Deploy apt sources.list
  template: src=etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  tags:
    - common-all

- apt: update_cache=yes
  tags:
    - packages
    - common-all

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - etckeeper
    - fail2ban
    - gawk
    - git
    - less
    - libpam-yubico
    - ncdu
    - tmux
    - tree
    - unzip
    - vim
    - vnstat
    - wget
    - whois
    - zip
  tags:
    - packages
    - common-all

# KVM servers run openntpd; usually not recommended to install both.
- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - ntpdate
  when: "'kvm-servers' not in group_names"
  tags:
    - packages
    - common-all
