---

- name: Create system users
  user: name={{ item | basename }} shell="/bin/bash"
  with_items: "{{ ssh_users }}"
  tags:
    - sshuserkeys

- name: Deploy ssh user keys
  authorized_key: user={{ item }} key="{{ lookup('file', '../sshkeys/' + item + '.pub') }}"
  with_items: "{{ ssh_users }}"
  tags:
    - sshuserkeys

- name: Add priviledged users to sudo, adm, www-editors groups.
  user: name={{ item }} groups="{{ item }},sudo,adm,www-editors" group="{{ item }}" append=yes
  with_items: "{{ root_sudoers }}"
  tags:
    - sshuserkeys
    - sshuserkeys-sudoers
