---

- name: Create system users
  user: name={{ item | basename | regex_replace('\.pub$', '') }} shell="/bin/bash"
  with_fileglob:
    - ../sshkeys/*.pub
  tags:
    - sshuserkeys

- name: Deploy ssh user keys
  authorized_key: user={{ item | basename | regex_replace('\.pub$', '') }} key="{{ lookup('file', item) }}"
  with_fileglob:
    - ../sshkeys/*.pub
  tags:
    - sshuserkeys
- name: Add priviledged users to sudo and adm groups
  user: name={{ item }} groups="{{ item }},sudo,adm,www-editors" group="{{ item }}" append=yes
  with_items: "{{ root_sudoers }}"
  tags:
    - sshuserkeys
    - sshuserkeys-sudoers

# TODO: per-server, ex: /etc/ansible/files/sshkeys/{{ inventory_hostname }}/*.pub
