---

# These packages have been used with Xenial+buildkit:
# See also: do_system_xenial
# https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L307

# Makes it easier to eventually switch between different versions (ex: 5.6).
# TODO: cleanup so that we have only one PHP role for all versions.

- name: show the groups the host(s) are in
  debug:
    msg: "{{group_names}}"
  when: "'apache-serves' not in group_names"
  tags:
    - php
    - php-apache

- apt: name=python-apt state=present install_recommends=no
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "24")
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x7BF576066ADA65728FC7E70A8C47BE8E75BCA694"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "24")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/certbot/certbot/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- name: Debian | Add Sury.org apt reporitory key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg
  when: ansible_distribution == "Debian"
  tags:
    - php

- apt_repository:
    repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes
  when: (ansible_distribution == "Debian")
  tags: php

- name: Install PHP Modules
  apt: 
    state: present
    install_recommends: no
    name:
      - php{{ php_version }}-cli
      - php{{ php_version }}-common
      - php{{ php_version }}-curl
      - php{{ php_version }}-fpm
      - php{{ php_version }}-dev
      - php{{ php_version }}-gd
      - php{{ php_version }}-imap
      - php{{ php_version }}-intl
      - php{{ php_version }}-json
      - php{{ php_version }}-ldap
      - php{{ php_version }}-mbstring
      - php{{ php_version }}-imagick 
      - php{{ php_version }}-mysql
      - php{{ php_version }}-opcache
      - php{{ php_version }}-readline
      - php{{ php_version }}-recode
      - php{{ php_version }}-soap
      - php{{ php_version }}-sqlite3
      - php{{ php_version }}-xml
      - php{{ php_version }}-xmlrpc
      - php{{ php_version }}-xsl
      - php{{ php_version }}-zip
      - php{{ php_version }}-bcmath
  tags: php

- name: Install apache webserver
  apt: 
    state: present
    install_recommends: no
    name:
      - apache2
      - libapache2-mod-php{{ php_version }}
  when: "'apache-servers' in group_names"
  tags: 
    - php-apache
    - php

- apt: 
    state: present
    install_recommends: no
    name:
      - certbot
      - python3-certbot-apache
  when: "'apache-servers' in group_names"
  tags: 
    - php-apache
    - php

- apt: 
    state: present
    install_recommends: no
    name:
      - nginx
      - php{{ php_version }}-fpm
      - python3-certbot-nginx
  when: "'apache-servers' not in group_names"
  tags:
    - php-nginx
    - php

- name: Deploy JMA PHP Customisation
  template:
    src=etc/php/{{ php_version }}/mods-available/90-jma.ini
    dest=/etc/php/{{ php_version }}/mods-available/90-jma.ini
    owner=root group=root mode=0644
  tags:
    - php-config
    - php

- name: Symlink JMA PHP Customisation for Apache
  file:
    src: /etc/php/{{ php_version }}/mods-available/90-jma.ini
    dest: /etc/php/{{ php_version }}/apache2/conf.d/90-jma.ini
    owner: root
    group: root
    state: link
  when: "'apache-servers' in group_names"
  notify: restart apache
  tags:
    - php-config
    - php

- name: Symlink JMA PHP Customisation for php-fpm
  file: src="/etc/php/{{ php_version }}/mods-available/90-jma.ini" dest="/etc/php/{{ php_version }}/fpm/conf.d/90-jma.ini" owner=root group=root state=link
  notify: restart php-fpm
  when: "'apache-servers' not in group_names"
  tags:
    - php-config
    - php

- name: Enable PHP Module
  apache2_module:
    state: present
    name: php{{ php_version }}
  notify: restart apache
  when: "'apache-servers' in group_names"
  tags: php

- name: Enable Apache rewrite works
  apache2_module:
    state: present
    name: rewrite
  notify: restart apache
  when: "'apache-servers' in group_names"
  tags: 
    - php
    - php-apache

- name: Add www-data into www-editors group
  user:
    name: 'www-data'
    groups: 'www-data,www-editors'
    append: yes
  when: "'local-servers' not in group_names"
  tags: 
    - php
    - php-apache
    - php-nginx

- name: Ensure that apache www-data umask is set right
  lineinfile:
    path: /etc/apache2/envvars
    line: 'umask 0002'
    insertbefore: BOF
  when: "'apache-servers' in group_names"
  notify: restart apache
  tags:
    - php
    - php-apache

- name: Ubuntu | Install Percona key
  apt_key: keyserver=keys.gnupg.net id=8507EFA5 state=present
  when: "'percona-servers' in group_names"
  tags:
    - php
    - php-percona

- name: ubuntu | install percona repository
  apt_repository: repo="deb http://repo.percona.com/apt {{ ansible_distribution_release }}  main" state=present
  when: "'percona-servers' in group_names"
  tags:
    - php
    - php-percona

- name: ubuntu | install percona soruce repository
  apt_repository: repo="deb-src http://repo.percona.com/apt {{ ansible_distribution_release }} main" state=present
  when: "'percona-servers' in group_names"
  tags:
    - php
    - php-percona

- name: ubuntu | Install python packages
  apt: 
    state: present
    install_recommends: no
    name:
      - vim
      - python-pycurl
      - python-mysqldb
  when: "'percona-servers' in group_names"
  tags:
    - php
    - php-percona

- name: ubuntu | Install Percona packages
  become: yes
  apt: 
    state: present
    install_recommends: no
    name:
      - percona-server-common-5.7
      - percona-server-client-5.7
      - percona-server-server-5.7
  environment:
    DEBIAN_FRONTEND: noninteractive
  when: "'percona-servers' in group_names"
  tags:
    - php
    - php-percona

- name: Debian | Add MariaDB apt key
  apt_key:
    url: "https://mariadb.org/mariadb_release_signing_key.asc"
    state: present
    keyring: /etc/apt/trusted.gpg.d/mariadb.gpg
#  when: ansible_distribution == "Debian" || ansible_distribution == "Ubuntu"
  tags:
    - php-mariadb

- apt_repository:
    repo="deb [arch=amd64,arm64,ppc64el] https://mirror.rackspace.com/mariadb/repo/{{ mariadb_version }}/debian {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes
  when: (ansible_distribution == "Debian")
  tags: 
    - php-mariadb

- apt_repository:
    repo="deb [arch=amd64,arm64,ppc64el] https://mirror.rackspace.com/mariadb/repo/{{ mariadb_version }}/ubuntu {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu")
  tags: 
    - php-mariadb


- name: Install MariaDB
  apt: 
    state: present
    install_recommends: no
    name:
      - mariadb-server
      - mariadb-server-{{ mariadb_version }}
      - mariadb-client
      - mariadb-client-{{ mariadb_version }}
#  when: ansible_distribution == "Debian" || ansible_distribution == "Ubuntu"
  tags: 
    - php-mariadb

- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/jma.cnf
    dest=/etc/mysql/conf.d/jma.cnf
    owner=root group=root mode=0644
  tags:
    - php-mysql
    - php-mariadb

- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/jma.cnf
    dest=/etc/mysql/mariadb.conf.d/60-jma.cnf
    owner=root group=root mode=0644
  when: (ansible_distribution == "Debian")
  tags:
    - php-mysql
    - php-mariadb

- name: Drush | Install Drush for use on servers
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.4.0/drush.phar
    dest: /usr/local/bin/drush
    mode: 775
  when: drush_install
  tags:
    - php-drush

- name: WP-CLI | Install WP-CLI for use on servers
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 775
  when: wp_cli_install
  tags:
    - php-wp

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: php-composer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  tags: php-composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  tags: php-composer

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  tags: php-composer

- name: CV | Install CV as another tool to use
  get_url:
    url: https://download.civicrm.org/cv/cv.phar
    dest: /usr/local/bin/cv
    mode: 775
  when: cv_install
  tags: php-cv
