---

# These packages have been used with Xenial+buildkit:
# See also: do_system_xenial
# https://github.com/civicrm/civicrm-buildkit/blob/master/bin/civi-download-tools#L307

# Makes it easier to eventually switch between different versions (ex: 5.6).
# TODO: cleanup so that we have only one PHP role for all versions.

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    python-apt
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4F4EA0AAE5267A6C"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x14AA40EC0831756756D7F66C4F4EA0AAE5267A6C"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- apt_key:
    url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x7BF576066ADA65728FC7E70A8C47BE8E75BCA694"
    state=present
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "16")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- apt_repository:
    repo='deb http://ppa.launchpad.net/certbot/certbot/ubuntu {{ ansible_distribution_release }} main'
    state=present
    update_cache=yes
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- name: Debian | Add Sury.org apt reporitory key
  apt_key:
    url: "https://packages.sury.org/php/apt.gpg"
    state: present
    keyring: /etc/apt/trusted.gpg.d/php.gpg
  when: ansible_distribution == "Debian"
  tags:
    - php

- apt_repository:
    repo="deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state=present
    update_cache=yes
  when: (ansible_distribution == "Debian")
  tags: php

- name: Install PHP Modules
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - php{{ php_version }}-cli
    - php{{ php_version }}-common
    - php{{ php_version }}-curl
    - php{{ php_version }}-fpm
    - php{{ php_version }}-dev
    - php{{ php_version }}-gd
    - php{{ php_version }}-imap
    - php{{ php_version }}-intl
    - php{{ php_version }}-json
    - php{{ php_version }}-ldap
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-imagick 
    - php{{ php_version }}-mysql
    - php{{ php_version }}-opcache
    - php{{ php_version }}-readline
    - php{{ php_version }}-recode
    - php{{ php_version }}-soap
    - php{{ php_version }}-sqlite3
    - php{{ php_version }}-xml
    - php{{ php_version }}-xmlrpc
    - php{{ php_version }}-xsl
    - php{{ php_version }}-zip
    - php{{ php_version }}-bcmath
    - apache2
    - libapache2-mod-php{{ php_version }}
  tags: php

- apt: name={{ item }} state=present install_recommends=no
  with_items:
    - certbot
    - python3-certbot-apache
  when: (ansible_distribution == "Ubuntu") and (ansible_lsb.major_release < "20")
  tags: php

- name: Enable PHP Module
  apache2_module:
    state: present
    name: php{{ php_version }}
  tags: php

- name: Enable Apache rewrite works
  apache2_module:
    state: present
    name: rewrite
  tags: php

- name: Add www-data into www-editors group
  user:
    name: 'www-data'
    groups: 'www-data,www-editors'
    append: yes
  tags: php

- name: Install MariaDB
  apt: name={{ item }} state=present install_recommends=no
  with_items:
    - mariadb-server
    - mariadb-client
  when: (ansible_distribution == "Debian")
  tags: php

- name: MySQL | Deploy our MySQL configuration overrides
  template:
    src=etc/mysql/conf.d/jma.cnf
    dest=/etc/mysql/conf.d/jma.cnf
    owner=root group=root mode=0644
  tags:
    - php-mysql
    - php-mariadb

- name: Drush | Install Drush for use on servers
  get_url:
    url: https://github.com/drush-ops/drush/releases/download/8.4.0/drush.phar
    dest: /usr/local/bin/drush
    mode: 775
  when: drush_install
  tags:
    - php-drush

- name: WP-CLI | Install WP-CLI for use on servers
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /usr/local/bin/wp
    mode: 775
  when: wp_cli_install
  tags:
    - php-wp

- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: php-composer

- name: install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  tags: php-composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
  args:
    creates: /usr/local/bin/composer
  tags: php-composer

- name: make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  tags: php-composer

- name: CV | Install CV as another tool to use
  get_url:
    url: https://download.civicrm.org/cv/cv.phar
    dest: /usr/local/bin/cv
    mode: 775
  when: cv_install
  tags: php-cv
